services:
  cafeorder-mysql:
    container_name: jcafe-order-mysql
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always

  cafeorder-mongo:
    container_name: jcafe-order-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./mongo/data:/data
    restart: always

  cafeorder-redis:
    container_name: jcafe-order-redis
    image: redis:6
    ports:
      - "6379:6379"
    restart: always
